### ISSUE TITLE
[Feature]: switch region command

### ISSUE THREAD

**Issue by geekingfrog** [beyond-all-reason/teiserver#356] opened 2024-07-10 11:53 UTC
### Describe the Feature

It happens fairly often that as Australia goes to sleep EU wakes up, or EU gives way for US players, the same lobby will continue on but is now hosted in a region that almost none of the current players are located in. If the lobby has a queue and even if it doesn't, getting everyone to switch to a region appropriate lag-free host is difficult.

Teiserver already has a command `$splitlobby` which lets a subset of players move to a different host if the current one has too many players. We could maybe add a similar command `$switchregion` that lets everyone in the lobby move to another host in a different region.

### Expected Behavior

So e.g. $switchregion eu initiates a teiserver vote. Players then have to vote with $y and if more than 50 % of the players in the lobby vote yes then everyone will be moved to an EU host.

Preferably players would get moved first (so they keep their spot as players) and people in queue next (preferably queue order is preserved) and then lastly the spectators.

### Additional context

suggestion in discord: https://discord.com/channels/549281623154229250/1255905272854085734

**Comment by p2004a** [comment] 2024-07-11 14:11
Related issue, this issue is likely a duplicate to a high degree: https://github.com/beyond-all-reason/teiserver/issues/174#issue-1928941317

**Comment by L-e-x-o-n** [comment] 2024-08-21 15:43
Closing as a duplicate of #94 . Please continue discussion there.

**Closed** 2024-08-21 15:47 UTC
Labels: feature request
