### ISSUE TITLE
Add command/something to move lobby between servers without any impact

### ISSUE THREAD

**Issue by p2004a** [beyond-all-reason/teiserver#174] opened 2023-10-05 19:38 UTC
Currently there is `$splitlobby` that allows players to be moved to a different lobby, it works by finding an empty lobby and moving players there.

This feature request is for some way for teiserver to be able to automatically move players to an entirely new lobby, in the same region, when the current lobby they are in is being stopped.

This is to allow a more seamless restarts and maintenance of spads servers.

**Comment by p2004a** [comment] 2023-10-05 20:15
I believe command might be the best, but maybe there are other good alternatives I don't know about. But let's say it's command, then yes: command that can be called by mod, admin, host itself, that:

1. Creates a new empty room:
   - In the same SPADS cluster if that cluster is available (it's not when we kill coordinator, but lobbies are still around)
   - In the same region, if there are some available hosts in the region (e.g. can be a problem to satisfy for AU1)
   - Somewhere else
2. Set ups the new empty room in exactly the same settings as original one
3. Moves all users and specs to the new lobby
4. Post update in the new lobby that they were being moved

**Comment by Teifion** [comment] 2023-10-05 20:16
That seems reasonable and straight forward.

**Comment by L-e-x-o-n** [comment] 2024-04-07 13:59
The solution to this could also be used for issue #94

**Comment by L-e-x-o-n** [comment] 2024-08-21 15:43
Closing as a duplicate of #94

**Closed by L-e-x-o-n** 2024-08-21 15:43 UTC
Labels: feature request
