### ISSUE TITLE
[Feature]: Allow the ability to prevent uncertainty increase

### ISSUE THREAD

**Issue by jauggy** [beyond-all-reason/teiserver#359] opened 2024-07-12 08:29 UTC
### Describe the Feature

Currently due to tau, it's possible for uncertainty to increase after rating a match. Allow the admin to set a flag (true/false) to prevent uncertainty increase.

### Expected Behavior
Admin should have a setting they can set to prevent uncertainty aka sigma increase. When enabled it will pass an additional parameter to openskill library.

### Additional context

Inside the elixir openskill library we already have this:
```
  def rate(rating_groups, options \\ []) do
    defaults = [
      weights: Util.default_weights(rating_groups),
      ranks: Util.default_ranks(rating_groups),
      model: Openskill.PlackettLuce,
      tau: @env.tau,
      prevent_sigma_increase: @env.prevent_sigma_increase
    ]

    options = Keyword.merge(defaults, options) |> Enum.into(%{})
```

This means we can pass in `prevent_sigma_increase: true` as an option

**Comment by StanczakDominik** [comment] 2024-07-17 18:50
Seems to me to be a duplicate of #319 :)

**Comment by L-e-x-o-n** [comment] 2024-08-21 15:34
Closing as duplicate of #319.

**Closed by L-e-x-o-n** 2024-08-21 15:34 UTC
Labels: feature request
